version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPOTIFY_REDIRECT_URL: "http://loonaboycott.com:8080/auth/spotify/callback"
      YOUTUBE_REDIRECT_URL: "http://loonaboycott.com:8080/auth/youtube/callback"
      REDIS_URL: "redis:6379"


  redis:
    image: redis:latest
    ports:
      - "6379:6379"