version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"